name = "flinkedlist"
version = "1.0.0"
license = "MIT"
author = "Yuichiro Sakamoto"
maintainer = "62064838+sakamoti@users.noreply.github.com"
copyright = "Copyright 2023, Yuichiro Sakamoto"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

